// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8q7iFJ-CozKWYgPJrDomRSHlRe_YENrc',
    appId: '1:375028742957:web:11beccf219b8036072b1a4',
    messagingSenderId: '375028742957',
    projectId: 'tourist-app-8112d',
    authDomain: 'tourist-app-8112d.firebaseapp.com',
    storageBucket: 'tourist-app-8112d.appspot.com',
    measurementId: 'G-SHKK8FT4LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxFG4-F_PcUPC7NwsrKMIxSct6JreM9mQ',
    appId: '1:375028742957:android:9c8fad417400a84972b1a4',
    messagingSenderId: '375028742957',
    projectId: 'tourist-app-8112d',
    storageBucket: 'tourist-app-8112d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuVKfrN_eRBom9BjEORwQaflChAgQeB-M',
    appId: '1:375028742957:ios:4d87ba7efb06dd8e72b1a4',
    messagingSenderId: '375028742957',
    projectId: 'tourist-app-8112d',
    storageBucket: 'tourist-app-8112d.appspot.com',
    iosClientId: '375028742957-aqk4bo8fspmddjmlv31k5lj3pdpj8bqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuVKfrN_eRBom9BjEORwQaflChAgQeB-M',
    appId: '1:375028742957:ios:0878d0b115d077eb72b1a4',
    messagingSenderId: '375028742957',
    projectId: 'tourist-app-8112d',
    storageBucket: 'tourist-app-8112d.appspot.com',
    iosClientId: '375028742957-db2jpkpcont27hd5teiseoev8rdgoi4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristApp.RunnerTests',
  );
}
